### ISSUE TITLE
运行train.py报错  'MujocoModel' object has no attribute 'to'

### ISSUE THREAD

**Issue by Hgy-ang** [PaddlePaddle/PaddleRobotics#11]
使用python train.py时报如下错误

Traceback (most recent call last):
  File "/home/ros/PaddleRobotics/QuadrupedalRobots/ETGRL/train.py", line 508, in <module>
    main()
  File "/home/ros/PaddleRobotics/QuadrupedalRobots/ETGRL/train.py", line 331, in main
    critic_lr=CRITIC_LR)
  File "/home/ros/PaddleRobotics\QuadrupedalRobots\ETGRL\alg\sac.py", line 53, in __init__
    self.model = model.to(device)
AttributeError: 'MujocoModel' object has no attribute 'to'

**Comment by woderrrrr** [comment]
我也有这个问题，请问您解决了吗？

**Comment by bld2013** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到您的邮件，灰常感谢！

**Comment by woderrrrr** [comment]
> 使用python train.py时报如下错误
> 
> Traceback (most recent call last): File "/home/ros/PaddleRobotics/QuadrupedalRobots/ETGRL/train.py", line 508, in main() File "/home/ros/PaddleRobotics/QuadrupedalRobots/ETGRL/train.py", line 331, in main critic_lr=CRITIC_LR) File "/home/ros/PaddleRobotics\QuadrupedalRobots\ETGRL\alg\sac.py", line 53, in **init** self.model = model.to(device) AttributeError: 'MujocoModel' object has no attribute 'to'

我也有这个问题，请问您解决了吗？
