### ISSUE TITLE
运行 python train.py --task_mode stairstair --ETG_path data/origin_ETG/ESStair_origin.npz报错

### ISSUE THREAD

**Issue by zhaojiu97** [PaddlePaddle/PaddleRobotics#13]
pybullet build time: Feb 10 2022 08:59:07
C:\Users\zhaojiu\anaconda3\lib\site-packages\rlschool\quadrupedal\robots\a1.py:92: RuntimeWarning: invalid value encountered in arccos
  theta_knee = -np.arccos(
[03-23 17:42:13 MainThread @logger.py:242] Argv: train.py --task_mode stairstair --ETG_path data/origin_ETG/ESStair_origin.npz
cuda
ETG_param_init: (12,)
{'dis': 1, 'motor': 1, 'imu': 1, 'contact': 1, 'footpose': 0, 'ETG': 1, 'ETG_obs': 0, 'dynamic_vec': 0, 'force_vec': 0, 'noise': 0, 'RNN': {'time_steps': 5, 'time_interval': 1, 'mode': 'None'}}
argv[0]=
starting thread 0
started testThreads thread 0 with threadHandle 0000000000000EF0
argc=3
argv[0] = --unused
argv[1] =
argv[2] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
Version = 4.6.0 NVIDIA 472.19
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2
b3Printf: Selected demo: Physics Server
starting thread 0
started MotionThreads thread 0 with threadHandle 000000000000109C
MotionThreadFunc thread started
c:\users\zhaojiu\gym\gym\spaces\box.py:78: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
C:\Users\zhaojiu\anaconda3\lib\site-packages\rlschool\quadrupedal\robots\minitaur.py:188: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated si
nce Python 3.3, and in 3.9 it will stop working
  if isinstance(motor_kp, (collections.Sequence, np.ndarray)):
obs_dim: 49
Traceback (most recent call last):
  File "train.py", line 523, in <module>
    main()
  File "train.py", line 452, in main
    ETG_info = np.load(args.load[:-3] + ".npz")
  File "C:\Users\zhaojiu\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '.npz'
numActiveThreads = 0
stopping threads
Thread with taskId 0 with handle 000000000000109C exiting
Thread TERMINATED
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 with handle 0000000000000EF0 exiting
Thread TERMINATED

**Comment by zhaojiu97** [comment]
在train.py 中，将eval改为1以后运行，提示：
Argv: D:/Quadruped_Robot/PaddleRobotics/QuadrupedalRobots/ETGRL/train.py
cuda
{'dis': 1, 'motor': 1, 'imu': 1, 'contact': 1, 'footpose': 0, 'ETG': 1, 'ETG_obs': 0, 'dynamic_vec': 0, 'force_vec': 0, 'noise': 0, 'RNN': {'time_steps': 5, 'time_interval': 1, 'mode': 'None'}}
argv[0]=
starting thread 0
started testThreads thread 0 with threadHandle 0000000000000154
argc=3
argv[0] = --unused
argv[1] = 
argv[2] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
Version = 4.6.0 NVIDIA 472.19
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2
b3Printf: Selected demo: Physics Server
starting thread 0
started MotionThreads thread 0 with threadHandle 0000000000001100
MotionThreadFunc thread started
c:\users\zhaojiu\gym\gym\spaces\box.py:78: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
C:\Users\zhaojiu\anaconda3\lib\site-packages\rlschool\quadrupedal\robots\minitaur.py:188: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  if isinstance(motor_kp, (collections.Sequence, np.ndarray)):
obs_dim: 49
Traceback (most recent call last):
  File "C:\Users\zhaojiu\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-d0304541f55b>", line 1, in <module>
    runfile('D:/Quadruped_Robot/PaddleRobotics/QuadrupedalRobots/ETGRL/train.py', wdir='D:/Quadruped_Robot/PaddleRobotics/QuadrupedalRobots/ETGRL')
  File "C:\Program Files\JetBrains\PyCharm 2021.2.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.2.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Quadruped_Robot/PaddleRobotics/QuadrupedalRobots/ETGRL/train.py", line 523, in <module>
    main()
  File "D:/Quadruped_Robot/PaddleRobotics/QuadrupedalRobots/ETGRL/train.py", line 452, in main
    ETG_info = np.load(args.load[:-3] + ".npz")
  File "C:\Users\zhaojiu\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '.npz'

**Comment by KiriyamaGK** [comment]
你好，我有差不多的问题，请问解决了吗

**Comment by bld2013** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到您的邮件，灰常感谢！
