### ISSUE TITLE
Evaluation in simulation报错

### ISSUE THREAD

**Issue by JeffXu1** [PaddlePaddle/PaddleRobotics#8]
使用python train.py命令评估模型时报如下错误
python train.py --task_mode stairstair --eval 1 --load data/model/StairStair_3_itr_960231.pt
[10-20 10:50:54 MainThread @logger.py:242] Argv: train.py --task_mode stairstair --eval 1 --load data/model/StairStair_3_itr_960231.pt
pybullet build time: Oct 11 2021 20:59:00
/home/xh/PycharmProjects/pythonProject2/venv/lib/python3.7/site-packages/rlschool-1.0.2-py3.7.egg/rlschool/quadrupedal/robots/a1.py:94: RuntimeWarning: invalid value encountered in arccos
  (2 * l_low * l_up))
Traceback (most recent call last):
  File "train.py", line 508, in <module>
    main()
  File "train.py", line 309, in main
    enable_action_filter=args.enable_action_filter)
  File "/home/xh/PycharmProjects/pythonProject2/venv/lib/python3.7/site-packages/rlschool-1.0.2-py3.7.egg/rlschool/__init__.py", line 17, in make_env
    raise Exception("rlschool.make_env is deprecated. Please do \"import rlschool.xxxenv\" and use gym.make instead")
Exception: rlschool.make_env is deprecated. Please do "import rlschool.xxxenv" and use gym.make instead

**Comment by WorldEditors** [comment]
This is probably due to our update on RLSchool / MetaGym environment. 
Starting from RLSchool 1.0.3, we are changing the entrance from 

rlschool.make_env("XXX")

to

import gym
import metagym.quadrupedal
gym.make("XXX")

To make sure the current version of PaddleRobotics work for you, please ensure that your are installing rlschool==1.0.2 by using 

pip install rlschool==1.0.2

If you are using the newest version of MetaGym.
please check https://github.com/PaddlePaddle/MetaGym/tree/master/metagym/quadrupedal
